/* ==========================================================================
   Renders the page from js/site.js (your config) and js/photos.js
   (generated by ./update). You shouldn't need to edit this file.
   ========================================================================== */

(function () {
  "use strict";

  var SITE = window.SITE || {};
  var PHOTOS = window.PHOTOS || {};
  var $ = function (id) { return document.getElementById(id); };

  var reducedMotion = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  var finePointer = window.matchMedia("(hover: hover) and (pointer: fine)").matches;

  /* ---------------------------------------------------------------- theme */

  var root = document.documentElement;
  try {
    var saved = localStorage.getItem("theme");
    if (saved === "light" || saved === "dark") root.setAttribute("data-theme", saved);
  } catch (e) {}

  $("theme-toggle").addEventListener("click", function () {
    var isLight = root.getAttribute("data-theme")
      ? root.getAttribute("data-theme") === "light"
      : window.matchMedia("(prefers-color-scheme: light)").matches;
    var next = isLight ? "dark" : "light";
    root.setAttribute("data-theme", next);
    try { localStorage.setItem("theme", next); } catch (e) {}
  });

  var reveal = makeReveal();

  /* ----------------------------------------------------------- 1. hero */

  if (SITE.name) {
    $("hero-name").textContent = SITE.name;
    document.querySelector(".nav__name").textContent = SITE.name;
    document.title = SITE.name;
  }
  $("hero-caption").textContent = SITE.caption || "";
  $("hero-caption").hidden = !SITE.caption;
  $("hero-tagline").textContent = SITE.tagline || "";
  $("grid-intro").textContent = SITE.gridIntro || "";

  /* -------------------------------------------------- 2. interests grid */

  var interests = SITE.interests || [];
  var grid = $("grid");

  interests.forEach(function (item, i) {
    var photos = PHOTOS[item.id] || [];
    var cover = photos[0];

    var card = document.createElement(cover ? "button" : "div");
    card.className = "card" + (cover ? "" : " card--empty");

    if (cover) {
      card.type = "button";
      card.setAttribute("aria-label", "Open photos: " + item.title);
      card.addEventListener("click", function () { openCarousel(item, photos, 0); });

      var img = document.createElement("img");
      // Tiles use the small copy; the carousel loads the full photo on open.
      img.src = cover.thumb || cover.src;
      img.alt = "";
      // First row loads immediately; everything below the fold waits.
      img.loading = i < 4 ? "eager" : "lazy";
      img.decoding = "async";
      if (cover.w && cover.h) { img.width = cover.w; img.height = cover.h; }
      img.addEventListener("load", function () { img.classList.add("is-loaded"); });
      // A missing file used to render as a permanent black rectangle. Try the
      // full-size photo first (thumbnails may not have been generated), and
      // only fall back to the empty-folder placeholder if that fails too.
      var triedFull = false;
      img.addEventListener("error", function () {
        if (!triedFull && cover.thumb && img.getAttribute("src") !== cover.src) {
          triedFull = true;
          img.src = cover.src;
          return;
        }
        card.classList.add("card--broken");
        img.remove();
        var warn = document.createElement("span");
        warn.className = "card__hint";
        warn.innerHTML = "<strong>" + item.title + "</strong>Photo missing — run <code>./update</code>";
        card.appendChild(warn);
      });
      if (img.complete) img.classList.add("is-loaded");
      card.appendChild(img);

      // Title sits over the photo and only appears on hover / focus.
      var overlay = document.createElement("span");
      overlay.className = "card__overlay";

      var title = document.createElement("span");
      title.className = "card__title";
      title.textContent = item.title;
      overlay.appendChild(title);

      var count = document.createElement("span");
      count.className = "card__count";
      count.textContent = photos.length;
      overlay.appendChild(count);

      card.appendChild(overlay);

    } else {
      var hint = document.createElement("span");
      hint.className = "card__hint";
      var strong = document.createElement("strong");
      strong.textContent = item.title;
      hint.appendChild(strong);
      hint.appendChild(document.createTextNode("Add photos to "));
      var code = document.createElement("code");
      code.textContent = "photos/" + item.id + "/";
      hint.appendChild(code);
      card.appendChild(hint);
    }

    grid.appendChild(card);
    reveal.observe(card);
  });

  /* ------------------------------------------ 3. fun facts side carousel */

  var facts = SITE.showFunFacts
    ? (SITE.funFacts || []).filter(function (f) { return f && f.trim(); })
    : [];
  var isPlaceholder = function (f) { return /^\s*\[.*\]\s*$/.test(f); };
  var unfilled = facts.filter(isPlaceholder).length;

  var factText = $("factcar-text");
  var factDots = $("factcar-dots");
  var factIndex = 0;
  var factTimer = null;

  if (!facts.length) {
    // Drop the aside entirely and let the grid reclaim its column.
    $("facts").hidden = true;
    $("nav-facts").hidden = true;
    document.querySelector(".layout").classList.add("is-full");
  } else {
    facts.forEach(function (_, i) {
      var dot = document.createElement("button");
      dot.type = "button";
      dot.setAttribute("role", "tab");
      dot.setAttribute("aria-label", "Fact " + (i + 1));
      dot.addEventListener("click", function () { showFact(i, true); });
      factDots.appendChild(dot);
    });

    // A loud reminder so placeholders can't ship to an admissions officer.
    // It removes itself once every fact is written.
    if (unfilled) {
      var warn = $("facts-warn");
      warn.textContent = unfilled + " of " + facts.length +
        " still unwritten — write them in js/site.js before sharing this link.";
      warn.hidden = false;
    }

    showFact(0, false);
    startFacts();

    $("fact-prev").addEventListener("click", function () { showFact(factIndex - 1, true); });
    $("fact-next").addEventListener("click", function () { showFact(factIndex + 1, true); });

    // Don't rotate out from under someone who's reading or tabbing through.
    var car = $("factcar");
    ["mouseenter", "focusin"].forEach(function (ev) {
      car.addEventListener(ev, stopFacts);
    });
    ["mouseleave", "focusout"].forEach(function (ev) {
      car.addEventListener(ev, startFacts);
    });
    document.addEventListener("visibilitychange", function () {
      if (document.hidden) stopFacts(); else startFacts();
    });
  }

  function showFact(i, manual) {
    var n = facts.length;
    factIndex = (i % n + n) % n;
    var fact = facts[factIndex];
    var blank = isPlaceholder(fact);

    factText.classList.add("is-out");
    setTimeout(function () {
      factText.textContent = blank ? "Still to write" : fact;
      factText.classList.toggle("is-blank", blank);
      factText.classList.remove("is-out");
    }, reducedMotion ? 0 : 220);

    Array.prototype.forEach.call(factDots.children, function (dot, k) {
      dot.classList.toggle("is-on", k === factIndex);
      dot.setAttribute("aria-selected", String(k === factIndex));
    });

    if (manual) { stopFacts(); startFacts(); }
  }

  function startFacts() {
    stopFacts();
    if (facts.length < 2 || document.hidden) return;
    factTimer = setInterval(function () { showFact(factIndex + 1, false); }, 5200);
  }

  function stopFacts() {
    if (factTimer) { clearInterval(factTimer); factTimer = null; }
  }

  /* -------------------------------------------------------- 4. photolog */

  var photolog = SITE.photolog;
  var photologPhotos = photolog ? (PHOTOS[photolog.id] || []) : [];

  if (photologPhotos.length) {
    $("photolog-title").textContent = photolog.title;
    $("photolog-intro").textContent = photolog.blurb || "";
    var plGrid = $("photolog-grid");

    photologPhotos.forEach(function (photo, i) {
      var tile = document.createElement("button");
      tile.className = "plog";
      tile.type = "button";
      tile.setAttribute("aria-label", photo.caption
        ? "View photo: " + photo.caption
        : "View photo " + (i + 1) + " of " + photologPhotos.length);
      tile.addEventListener("click", function () {
        openCarousel(photolog, photologPhotos, i);
      });

      var im = document.createElement("img");
      im.src = photo.thumb || photo.src;
      im.alt = photo.caption || "";
      im.loading = i < 6 ? "eager" : "lazy";
      im.decoding = "async";
      if (photo.w && photo.h) { im.width = photo.w; im.height = photo.h; }
      im.addEventListener("load", function () { im.classList.add("is-loaded"); });
      var plTriedFull = false;
      im.addEventListener("error", function () {
        if (!plTriedFull && photo.thumb && im.getAttribute("src") !== photo.src) {
          plTriedFull = true;
          im.src = photo.src;
          return;
        }
        tile.remove();
      });
      if (im.complete) im.classList.add("is-loaded");
      tile.appendChild(im);

      if (photo.caption) {
        var cap = document.createElement("span");
        cap.className = "plog__cap";
        cap.textContent = photo.caption;
        tile.appendChild(cap);
      }

      plGrid.appendChild(tile);
      reveal.observe(tile);
    });

    $("nav-photolog-label").textContent = photolog.navLabel || photolog.title;
    $("photolog").hidden = false;
    $("nav-photolog").hidden = false;
  }

  /* ---------------------------------------------------------- 5. footer */

  var footerLinks = $("footer-links");
  (SITE.links || []).forEach(function (link) {
    if (!link.url) return;
    var a = document.createElement("a");
    a.href = link.url;
    a.textContent = link.label;
    if (!/^mailto:/.test(link.url)) {
      a.target = "_blank";
      a.rel = "noopener noreferrer";
    }
    footerLinks.appendChild(a);
  });

  /* ------------------------------------------------- reveal on scroll */

  function makeReveal() {
    if (!("IntersectionObserver" in window)) {
      return { observe: function (el) { el.classList.add("is-in"); } };
    }
    return new IntersectionObserver(function (entries, obs) {
      entries.forEach(function (e, k) {
        if (!e.isIntersecting) return;
        // Small stagger so a row doesn't pop in all at once.
        e.target.style.transitionDelay = Math.min(k * 45, 260) + "ms";
        e.target.classList.add("is-in");
        obs.unobserve(e.target);
      });
    }, { rootMargin: "0px 0px -6% 0px", threshold: 0.05 });
  }

  /* ====================================================================
     AMBIENT MOTION
     One rAF loop drives the cursor spotlight and the hero parallax, so
     mousemove never writes styles directly. Everything is transform /
     opacity only, and the whole block is skipped when the user has asked
     for reduced motion or has no real pointer.
     ==================================================================== */

  var nav = $("nav");
  var hero = document.querySelector(".hero");
  var spotlight = $("spotlight");

  var pointer = { x: window.innerWidth / 2, y: window.innerHeight * 0.4 };
  var eased = { x: pointer.x, y: pointer.y };
  var rafId = null;

  if (finePointer && !reducedMotion) {
    window.addEventListener("mousemove", function (e) {
      pointer.x = e.clientX;
      pointer.y = e.clientY;
      if (!spotlight.classList.contains("is-live")) spotlight.classList.add("is-live");
    }, { passive: true });

    // The loop runs continuously rather than being started per-mousemove and
    // latched off when it settles. A latch dies permanently if its frame is
    // ever dropped (page hidden mid-schedule, throttled tab); this recovers
    // on the next frame. Idle cost is one comparison — it writes nothing
    // while the cursor is still.
    startAmbient();
    document.addEventListener("visibilitychange", function () {
      if (document.hidden) stopAmbient(); else startAmbient();
    });
  }

  function startAmbient() {
    if (rafId === null) rafId = requestAnimationFrame(ambientLoop);
  }

  function stopAmbient() {
    if (rafId !== null) { cancelAnimationFrame(rafId); rafId = null; }
  }

  function ambientLoop() {
    var dx = pointer.x - eased.x;
    var dy = pointer.y - eased.y;

    if (Math.abs(dx) > 0.3 || Math.abs(dy) > 0.3) {
      // Ease toward the cursor so the light lags slightly behind it.
      eased.x += dx * 0.09;
      eased.y += dy * 0.09;

      root.style.setProperty("--mx", eased.x.toFixed(1) + "px");
      root.style.setProperty("--my", eased.y.toFixed(1) + "px");

      // Hero grid leans toward the cursor by a few pixels at most.
      var cx = (eased.x / window.innerWidth - 0.5);
      var cy = (eased.y / window.innerHeight - 0.5);
      root.style.setProperty("--px", (cx * 14).toFixed(2) + "px");
      root.style.setProperty("--py", (cy * 14).toFixed(2) + "px");
    }

    rafId = requestAnimationFrame(ambientLoop);
  }

  /* ---------------------------------------------------- scroll parallax */

  var scrollQueued = false;

  function onScroll() {
    if (scrollQueued) return;
    scrollQueued = true;
    requestAnimationFrame(function () {
      scrollQueued = false;
      var y = window.scrollY;

      nav.classList.toggle("is-stuck", y > 40);

      if (reducedMotion || !hero) return;
      var h = hero.offsetHeight || 1;
      if (y > h) return;  // stop doing work once the hero is off screen
      // Hero text drifts at ~72% of scroll speed and fades as it leaves.
      root.style.setProperty("--hero-shift", (y * 0.28).toFixed(1) + "px");
      root.style.setProperty("--hero-fade", Math.max(0, 1 - (y / h) * 1.35).toFixed(3));
    });
  }

  onScroll();
  window.addEventListener("scroll", onScroll, { passive: true });

  /* ====================================================================
     PHOTO CAROUSEL
     Images are only fetched when a card is opened, then neighbours are
     warmed in the background.
     ==================================================================== */

  var lb = $("lightbox");
  var lbImg = $("lb-img");
  var lbSpinner = $("lb-spinner");
  var lbDots = $("lb-dots");
  var current = { photos: [], index: 0 };
  var lastFocus = null;

  function openCarousel(item, photos, startAt) {
    current.photos = photos || [];
    if (!current.photos.length) return;

    lastFocus = document.activeElement;
    $("lb-title").textContent = item.title;
    $("lb-blurb").textContent = item.blurb || "";
    $("lb-blurb").hidden = !item.blurb;

    buildDots(current.photos.length);

    lb.hidden = false;
    document.body.classList.add("is-locked");
    requestAnimationFrame(function () { lb.classList.add("is-open"); });

    show(startAt || 0, 0);
    $("lb-close").focus();
  }

  function closeCarousel() {
    lb.classList.remove("is-open");
    document.body.classList.remove("is-locked");
    setTimeout(function () {
      lb.hidden = true;
      lbImg.removeAttribute("src");
    }, 280);
    if (lastFocus) lastFocus.focus();
  }

  function buildDots(n) {
    lbDots.innerHTML = "";
    // Dots get unreadable past a dozen; the counter carries it from there.
    lbDots.hidden = n < 2 || n > 12;
    if (lbDots.hidden) return;
    for (var i = 0; i < n; i++) {
      var dot = document.createElement("button");
      dot.className = "lb__dot";
      dot.type = "button";
      dot.setAttribute("role", "tab");
      dot.setAttribute("aria-label", "Photo " + (i + 1));
      dot.addEventListener("click", dotHandler(i));
      lbDots.appendChild(dot);
    }
  }

  function show(index, dir) {
    var n = current.photos.length;
    if (dir === undefined) dir = index > current.index ? 1 : -1;
    current.index = (index % n + n) % n;
    var photo = current.photos[current.index];

    lbImg.classList.remove("is-loaded");
    $("lb-error").hidden = true;
    lbSpinner.hidden = false;

    // Direction-aware slide: the incoming photo enters from the side you're
    // travelling towards, so paging feels like movement rather than a blink.
    if (dir && !reducedMotion) {
      lbImg.style.transition = "none";
      lbImg.style.transform = "translateX(" + (dir * 34) + "px)";
      requestAnimationFrame(function () {
        lbImg.style.transition = "";
        lbImg.style.transform = "";
      });
    }

    lbImg.src = photo.src;
    lbImg.alt = photo.caption || "";

    $("lb-caption").textContent = photo.caption || "";
    $("lb-count").textContent = (current.index + 1) + " / " + n;

    var multiple = n > 1;
    $("lb-prev").hidden = !multiple;
    $("lb-next").hidden = !multiple;

    Array.prototype.forEach.call(lbDots.children, function (dot, i) {
      dot.classList.toggle("is-on", i === current.index);
      dot.setAttribute("aria-selected", String(i === current.index));
    });

    // Warm the neighbours so arrowing through feels instant.
    [current.index + 1, current.index - 1].forEach(function (i) {
      var neighbour = current.photos[(i % n + n) % n];
      if (neighbour) new Image().src = neighbour.src;
    });
  }

  lbImg.addEventListener("load", function () {
    lbImg.classList.add("is-loaded");
    lbSpinner.hidden = true;
  });

  // Without this the spinner span forever on a missing file — which reads as
  // "buffering" rather than "broken".
  lbImg.addEventListener("error", function () {
    lbSpinner.hidden = true;
    lbImg.classList.remove("is-loaded");
    $("lb-error").hidden = false;
  });

  // A swipe ends in a click on whichever tap zone the finger lifted over, so
  // without this a single swipe would advance two photos.
  var suppressClick = false;

  $("lb-close").addEventListener("click", closeCarousel);
  $("lb-prev").addEventListener("click", function () {
    if (suppressClick) return;
    show(current.index - 1, -1);
  });
  $("lb-next").addEventListener("click", function () {
    if (suppressClick) return;
    show(current.index + 1, 1);
  });

  lb.addEventListener("click", function (e) {
    // Click the backdrop (not the photo or controls) to dismiss.
    if (e.target === lb || e.target.classList.contains("lb__figure")
        || e.target.classList.contains("lb__stage")) {
      closeCarousel();
    }
  });

  document.addEventListener("keydown", function (e) {
    if (lb.hidden) return;
    if (e.key === "Escape") closeCarousel();
    else if (e.key === "ArrowRight") show(current.index + 1, 1);
    else if (e.key === "ArrowLeft") show(current.index - 1, -1);
    else if (e.key === "Tab") {
      // Keep focus inside the dialog while it's open.
      var focusable = lb.querySelectorAll("button:not([hidden])");
      if (!focusable.length) return;
      var first = focusable[0];
      var last = focusable[focusable.length - 1];
      if (e.shiftKey && document.activeElement === first) {
        e.preventDefault(); last.focus();
      } else if (!e.shiftKey && document.activeElement === last) {
        e.preventDefault(); first.focus();
      }
    }
  });

  // Swipe.
  var touchX = null, touchY = null, dragged = false;

  lb.addEventListener("touchstart", function (e) {
    touchX = e.changedTouches[0].clientX;
    touchY = e.changedTouches[0].clientY;
    dragged = false;
  }, { passive: true });

  lb.addEventListener("touchmove", function (e) {
    if (touchX === null) return;
    var dx = e.changedTouches[0].clientX - touchX;
    var dy = e.changedTouches[0].clientY - touchY;
    if (Math.abs(dx) > 10 || Math.abs(dy) > 10) dragged = true;
  }, { passive: true });

  lb.addEventListener("touchend", function (e) {
    if (touchX === null) return;
    var dx = e.changedTouches[0].clientX - touchX;
    var dy = e.changedTouches[0].clientY - touchY;
    // Horizontal intent only, so vertical scrolling doesn't flip photos.
    if (Math.abs(dx) > 50 && Math.abs(dx) > Math.abs(dy)) {
      show(current.index + (dx < 0 ? 1 : -1), dx < 0 ? 1 : -1);
    }
    // Any real finger movement means this wasn't a tap — swallow the click
    // the browser is about to synthesise.
    if (dragged) {
      suppressClick = true;
      setTimeout(function () { suppressClick = false; }, 350);
    }
    touchX = touchY = null;
  }, { passive: true });

  // Trackpad / wheel paging. Latched so one flick moves exactly one photo
  // instead of racing through the whole set.
  var wheelLock = false;
  lb.addEventListener("wheel", function (e) {
    if (lb.hidden) return;
    e.preventDefault();
    if (wheelLock) return;
    var delta = Math.abs(e.deltaX) > Math.abs(e.deltaY) ? e.deltaX : e.deltaY;
    if (Math.abs(delta) < 12) return;
    wheelLock = true;
    show(current.index + (delta > 0 ? 1 : -1), delta > 0 ? 1 : -1);
    setTimeout(function () { wheelLock = false; }, 380);
  }, { passive: false });

  /* --------------------------------------------------- dots click wiring */

  function dotHandler(idx) {
    return function () { show(idx, idx > current.index ? 1 : -1); };
  }

})();
