// Generated by update.py — do not edit by hand.
// Add or rename photos in photos/, then run ./update
window.PHOTOS = {
  "abwa-mathematics": [
    {
      "src": "photos/abwa-mathematics/3dd3e482-5dba-4e4f-84a5-b4adaee4e74c.JPG",
      "caption": "",
      "w": 1280,
      "h": 1104,
      "thumb": "photos/_thumbs/abwa-mathematics/3dd3e482-5dba-4e4f-84a5-b4adaee4e74c.jpg"
    },
    {
      "src": "photos/abwa-mathematics/FullSizeRender.jpg",
      "caption": "",
      "w": 1800,
      "h": 1012,
      "thumb": "photos/_thumbs/abwa-mathematics/FullSizeRender.jpg"
    },
    {
      "src": "photos/abwa-mathematics/IMG_3327.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/abwa-mathematics/IMG_3327.jpg"
    },
    {
      "src": "photos/abwa-mathematics/IMG_3356.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/abwa-mathematics/IMG_3356.jpg"
    },
    {
      "src": "photos/abwa-mathematics/IMG_3359.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/abwa-mathematics/IMG_3359.jpg"
    },
    {
      "src": "photos/abwa-mathematics/IMG_3483.jpg",
      "caption": "",
      "w": 831,
      "h": 1800,
      "thumb": "photos/_thumbs/abwa-mathematics/IMG_3483.jpg"
    },
    {
      "src": "photos/abwa-mathematics/IMG_5296.jpg",
      "caption": "",
      "w": 1012,
      "h": 1800,
      "thumb": "photos/_thumbs/abwa-mathematics/IMG_5296.jpg"
    }
  ],
  "duke-of-edinburgh": [
    {
      "src": "photos/duke-of-edinburgh/IMG_2001.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/duke-of-edinburgh/IMG_2001.jpg"
    },
    {
      "src": "photos/duke-of-edinburgh/IMG_2008.jpg",
      "caption": "",
      "w": 1800,
      "h": 1350,
      "thumb": "photos/_thumbs/duke-of-edinburgh/IMG_2008.jpg"
    },
    {
      "src": "photos/duke-of-edinburgh/IMG_2015.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/duke-of-edinburgh/IMG_2015.jpg"
    },
    {
      "src": "photos/duke-of-edinburgh/IMG_2018.jpg",
      "caption": "",
      "w": 1800,
      "h": 1350,
      "thumb": "photos/_thumbs/duke-of-edinburgh/IMG_2018.jpg"
    },
    {
      "src": "photos/duke-of-edinburgh/IMG_2040.jpg",
      "caption": "",
      "w": 1800,
      "h": 1350,
      "thumb": "photos/_thumbs/duke-of-edinburgh/IMG_2040.jpg"
    },
    {
      "src": "photos/duke-of-edinburgh/IMG_2052.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/duke-of-edinburgh/IMG_2052.jpg"
    },
    {
      "src": "photos/duke-of-edinburgh/IMG_2058.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/duke-of-edinburgh/IMG_2058.jpg"
    },
    {
      "src": "photos/duke-of-edinburgh/IMG_2602.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/duke-of-edinburgh/IMG_2602.jpg"
    },
    {
      "src": "photos/duke-of-edinburgh/IMG_2623.jpg",
      "caption": "",
      "w": 1800,
      "h": 1350,
      "thumb": "photos/_thumbs/duke-of-edinburgh/IMG_2623.jpg"
    },
    {
      "src": "photos/duke-of-edinburgh/IMG_2630.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/duke-of-edinburgh/IMG_2630.jpg"
    },
    {
      "src": "photos/duke-of-edinburgh/IMG_2644.jpg",
      "caption": "",
      "w": 1800,
      "h": 1350,
      "thumb": "photos/_thumbs/duke-of-edinburgh/IMG_2644.jpg"
    },
    {
      "src": "photos/duke-of-edinburgh/IMG_2648.jpg",
      "caption": "",
      "w": 1800,
      "h": 1350,
      "thumb": "photos/_thumbs/duke-of-edinburgh/IMG_2648.jpg"
    }
  ],
  "esports": [
    {
      "src": "photos/esports/IMG_2119.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/esports/IMG_2119.jpg"
    },
    {
      "src": "photos/esports/IMG_25.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/esports/IMG_25.jpg"
    },
    {
      "src": "photos/esports/IMG_3651.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/esports/IMG_3651.jpg"
    },
    {
      "src": "photos/esports/IMG_3652.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/esports/IMG_3652.jpg"
    },
    {
      "src": "photos/esports/IMG_6190.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/esports/IMG_6190.jpg"
    },
    {
      "src": "photos/esports/IMG_6191%202.jpg",
      "caption": "",
      "w": 1800,
      "h": 1350,
      "thumb": "photos/_thumbs/esports/IMG_6191%202.jpg"
    },
    {
      "src": "photos/esports/IMG_6191.jpg",
      "caption": "",
      "w": 1800,
      "h": 1350,
      "thumb": "photos/_thumbs/esports/IMG_6191.jpg"
    },
    {
      "src": "photos/esports/IMG_6192.jpg",
      "caption": "",
      "w": 1800,
      "h": 1350,
      "thumb": "photos/_thumbs/esports/IMG_6192.jpg"
    },
    {
      "src": "photos/esports/IMG_6251.jpg",
      "caption": "",
      "w": 1800,
      "h": 1350,
      "thumb": "photos/_thumbs/esports/IMG_6251.jpg"
    }
  ],
  "gaming": [
    {
      "src": "photos/gaming/IMG_0191.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/gaming/IMG_0191.jpg"
    },
    {
      "src": "photos/gaming/IMG_0202.JPEG",
      "caption": "",
      "w": 1800,
      "h": 1251,
      "thumb": "photos/_thumbs/gaming/IMG_0202.jpg"
    },
    {
      "src": "photos/gaming/IMG_0240.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/gaming/IMG_0240.jpg"
    },
    {
      "src": "photos/gaming/IMG_02920.JPG",
      "caption": "",
      "w": 585,
      "h": 780,
      "thumb": "photos/_thumbs/gaming/IMG_02920.jpg"
    },
    {
      "src": "photos/gaming/IMG_0807.jpg",
      "caption": "",
      "w": 831,
      "h": 1800,
      "thumb": "photos/_thumbs/gaming/IMG_0807.jpg"
    },
    {
      "src": "photos/gaming/IMG_2694.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/gaming/IMG_2694.jpg"
    },
    {
      "src": "photos/gaming/IMG_2726.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/gaming/IMG_2726.jpg"
    },
    {
      "src": "photos/gaming/IMG_2729.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/gaming/IMG_2729.jpg"
    },
    {
      "src": "photos/gaming/IMG_2873.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/gaming/IMG_2873.jpg"
    },
    {
      "src": "photos/gaming/IMG_2928.jpg",
      "caption": "",
      "w": 1563,
      "h": 1613,
      "thumb": "photos/_thumbs/gaming/IMG_2928.jpg"
    },
    {
      "src": "photos/gaming/IMG_3216.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/gaming/IMG_3216.jpg"
    },
    {
      "src": "photos/gaming/IMG_3271.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/gaming/IMG_3271.jpg"
    },
    {
      "src": "photos/gaming/IMG_3308.jpg",
      "caption": "",
      "w": 1800,
      "h": 1251,
      "thumb": "photos/_thumbs/gaming/IMG_3308.jpg"
    },
    {
      "src": "photos/gaming/IMG_4809.jpg",
      "caption": "",
      "w": 1800,
      "h": 1251,
      "thumb": "photos/_thumbs/gaming/IMG_4809.jpg"
    },
    {
      "src": "photos/gaming/IMG_5333.jpg",
      "caption": "",
      "w": 1800,
      "h": 1251,
      "thumb": "photos/_thumbs/gaming/IMG_5333.jpg"
    },
    {
      "src": "photos/gaming/IMG_5451.jpg",
      "caption": "",
      "w": 1800,
      "h": 1251,
      "thumb": "photos/_thumbs/gaming/IMG_5451.jpg"
    },
    {
      "src": "photos/gaming/IMG_5686.jpg",
      "caption": "",
      "w": 1251,
      "h": 1800,
      "thumb": "photos/_thumbs/gaming/IMG_5686.jpg"
    },
    {
      "src": "photos/gaming/IMG_5864.jpg",
      "caption": "",
      "w": 1800,
      "h": 1251,
      "thumb": "photos/_thumbs/gaming/IMG_5864.jpg"
    },
    {
      "src": "photos/gaming/IMG_6003.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/gaming/IMG_6003.jpg"
    },
    {
      "src": "photos/gaming/IMG_6419.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/gaming/IMG_6419.jpg"
    },
    {
      "src": "photos/gaming/IMG_6457.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/gaming/IMG_6457.jpg"
    },
    {
      "src": "photos/gaming/IMG_7935.jpg",
      "caption": "",
      "w": 1800,
      "h": 1350,
      "thumb": "photos/_thumbs/gaming/IMG_7935.jpg"
    },
    {
      "src": "photos/gaming/IMG_87.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/gaming/IMG_87.jpg"
    },
    {
      "src": "photos/gaming/IMG_8704.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/gaming/IMG_8704.jpg"
    },
    {
      "src": "photos/gaming/IMG_8866.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/gaming/IMG_8866.jpg"
    },
    {
      "src": "photos/gaming/IMG_9006.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/gaming/IMG_9006.jpg"
    },
    {
      "src": "photos/gaming/IMG_9178.jpg",
      "caption": "",
      "w": 831,
      "h": 1800,
      "thumb": "photos/_thumbs/gaming/IMG_9178.jpg"
    },
    {
      "src": "photos/gaming/IMG_9179.jpg",
      "caption": "",
      "w": 831,
      "h": 1800,
      "thumb": "photos/_thumbs/gaming/IMG_9179.jpg"
    },
    {
      "src": "photos/gaming/IMG_9180.jpg",
      "caption": "",
      "w": 831,
      "h": 1800,
      "thumb": "photos/_thumbs/gaming/IMG_9180.jpg"
    },
    {
      "src": "photos/gaming/IMG_9181.jpg",
      "caption": "",
      "w": 831,
      "h": 1800,
      "thumb": "photos/_thumbs/gaming/IMG_9181.jpg"
    },
    {
      "src": "photos/gaming/IMG_9182.jpg",
      "caption": "",
      "w": 831,
      "h": 1800,
      "thumb": "photos/_thumbs/gaming/IMG_9182.jpg"
    },
    {
      "src": "photos/gaming/IMG_9278.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/gaming/IMG_9278.jpg"
    }
  ],
  "gym": [
    {
      "src": "photos/gym/IMG_1353.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/gym/IMG_1353.jpg"
    },
    {
      "src": "photos/gym/IMG_6945.JPG",
      "caption": "",
      "w": 1012,
      "h": 1800,
      "thumb": "photos/_thumbs/gym/IMG_6945.jpg"
    },
    {
      "src": "photos/gym/IMG_6971.JPG",
      "caption": "",
      "w": 1012,
      "h": 1800,
      "thumb": "photos/_thumbs/gym/IMG_6971.jpg"
    },
    {
      "src": "photos/gym/IMG_9177.jpg",
      "caption": "",
      "w": 831,
      "h": 1800,
      "thumb": "photos/_thumbs/gym/IMG_9177.jpg"
    }
  ],
  "iisc-uav": [
    {
      "src": "photos/iisc-uav/IMG_9791.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/iisc-uav/IMG_9791.jpg"
    },
    {
      "src": "photos/iisc-uav/IMG_9792.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/iisc-uav/IMG_9792.jpg"
    },
    {
      "src": "photos/iisc-uav/IMG_9794.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/iisc-uav/IMG_9794.jpg"
    },
    {
      "src": "photos/iisc-uav/IMG_9796.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/iisc-uav/IMG_9796.jpg"
    },
    {
      "src": "photos/iisc-uav/IMG_98.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/iisc-uav/IMG_98.jpg"
    },
    {
      "src": "photos/iisc-uav/IMG_9886.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/iisc-uav/IMG_9886.jpg"
    },
    {
      "src": "photos/iisc-uav/IMG_9891.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/iisc-uav/IMG_9891.jpg"
    },
    {
      "src": "photos/iisc-uav/IMG_9892.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/iisc-uav/IMG_9892.jpg"
    },
    {
      "src": "photos/iisc-uav/IMG_9894.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/iisc-uav/IMG_9894.jpg"
    },
    {
      "src": "photos/iisc-uav/IMG_9929.jpg",
      "caption": "",
      "w": 1800,
      "h": 1350,
      "thumb": "photos/_thumbs/iisc-uav/IMG_9929.jpg"
    },
    {
      "src": "photos/iisc-uav/IMG_9931.jpg",
      "caption": "",
      "w": 1800,
      "h": 1350,
      "thumb": "photos/_thumbs/iisc-uav/IMG_9931.jpg"
    },
    {
      "src": "photos/iisc-uav/IMG_9934.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/iisc-uav/IMG_9934.jpg"
    }
  ],
  "instilt-educate": [
    {
      "src": "photos/instilt-educate/IMG_1334.jpg",
      "caption": "",
      "w": 831,
      "h": 1800,
      "thumb": "photos/_thumbs/instilt-educate/IMG_1334.jpg"
    },
    {
      "src": "photos/instilt-educate/IMG_1335.jpg",
      "caption": "",
      "w": 831,
      "h": 1800,
      "thumb": "photos/_thumbs/instilt-educate/IMG_1335.jpg"
    },
    {
      "src": "photos/instilt-educate/IMG_5224.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/instilt-educate/IMG_5224.jpg"
    },
    {
      "src": "photos/instilt-educate/IMG_5225.jpg",
      "caption": "",
      "w": 1800,
      "h": 1350,
      "thumb": "photos/_thumbs/instilt-educate/IMG_5225.jpg"
    },
    {
      "src": "photos/instilt-educate/IMG_5549.jpg",
      "caption": "",
      "w": 1800,
      "h": 1251,
      "thumb": "photos/_thumbs/instilt-educate/IMG_5549.jpg"
    },
    {
      "src": "photos/instilt-educate/IMG_5821.jpg",
      "caption": "",
      "w": 1112,
      "h": 1423,
      "thumb": "photos/_thumbs/instilt-educate/IMG_5821.jpg"
    },
    {
      "src": "photos/instilt-educate/IMG_7827.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/instilt-educate/IMG_7827.jpg"
    },
    {
      "src": "photos/instilt-educate/IMG_7829.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/instilt-educate/IMG_7829.jpg"
    }
  ],
  "mun": [
    {
      "src": "photos/mun/IMG.jpeg",
      "caption": "",
      "w": 960,
      "h": 1280,
      "thumb": "photos/_thumbs/mun/IMG.jpg"
    },
    {
      "src": "photos/mun/IMG_0680.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/mun/IMG_0680.jpg"
    },
    {
      "src": "photos/mun/IMG_0692.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/mun/IMG_0692.jpg"
    },
    {
      "src": "photos/mun/IMG_0738.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/mun/IMG_0738.jpg"
    },
    {
      "src": "photos/mun/IMG_0755.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/mun/IMG_0755.jpg"
    },
    {
      "src": "photos/mun/IMG_5860%202.jpg",
      "caption": "",
      "w": 1800,
      "h": 1350,
      "thumb": "photos/_thumbs/mun/IMG_5860%202.jpg"
    },
    {
      "src": "photos/mun/IMG_5860.jpg",
      "caption": "",
      "w": 1800,
      "h": 1350,
      "thumb": "photos/_thumbs/mun/IMG_5860.jpg"
    },
    {
      "src": "photos/mun/IMG_9173.jpg",
      "caption": "",
      "w": 831,
      "h": 1800,
      "thumb": "photos/_thumbs/mun/IMG_9173.jpg"
    }
  ],
  "odoo-erp": [
    {
      "src": "photos/odoo-erp/1.jpeg",
      "caption": "",
      "w": 1800,
      "h": 1202,
      "thumb": "photos/_thumbs/odoo-erp/1.jpg"
    },
    {
      "src": "photos/odoo-erp/7E5FAE3E-CC70-4ED6-8BB2-E4A7AF3A6360.JPG",
      "caption": "",
      "w": 1012,
      "h": 1800,
      "thumb": "photos/_thumbs/odoo-erp/7E5FAE3E-CC70-4ED6-8BB2-E4A7AF3A6360.jpg"
    },
    {
      "src": "photos/odoo-erp/1777639553436.jpeg",
      "caption": "",
      "w": 1800,
      "h": 1202,
      "thumb": "photos/_thumbs/odoo-erp/1777639553436.jpg"
    },
    {
      "src": "photos/odoo-erp/EF85315A-21C5-4144-BE72-82840CEFE1A7.JPG",
      "caption": "",
      "w": 1012,
      "h": 1800,
      "thumb": "photos/_thumbs/odoo-erp/EF85315A-21C5-4144-BE72-82840CEFE1A7.jpg"
    },
    {
      "src": "photos/odoo-erp/IMG_9414.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/odoo-erp/IMG_9414.jpg"
    },
    {
      "src": "photos/odoo-erp/IMG_9415.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/odoo-erp/IMG_9415.jpg"
    },
    {
      "src": "photos/odoo-erp/IMG_9431.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/odoo-erp/IMG_9431.jpg"
    },
    {
      "src": "photos/odoo-erp/IMG_9456.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/odoo-erp/IMG_9456.jpg"
    },
    {
      "src": "photos/odoo-erp/IMG_9486.JPG",
      "caption": "",
      "w": 1012,
      "h": 1800,
      "thumb": "photos/_thumbs/odoo-erp/IMG_9486.jpg"
    },
    {
      "src": "photos/odoo-erp/IMG_9498.JPG",
      "caption": "",
      "w": 1012,
      "h": 1800,
      "thumb": "photos/_thumbs/odoo-erp/IMG_9498.jpg"
    }
  ],
  "pc-setup": [
    {
      "src": "photos/pc-setup/IMG_0001.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/pc-setup/IMG_0001.jpg"
    },
    {
      "src": "photos/pc-setup/IMG_0002.jpg",
      "caption": "",
      "w": 1800,
      "h": 1350,
      "thumb": "photos/_thumbs/pc-setup/IMG_0002.jpg"
    },
    {
      "src": "photos/pc-setup/IMG_0003.jpg",
      "caption": "",
      "w": 1800,
      "h": 1350,
      "thumb": "photos/_thumbs/pc-setup/IMG_0003.jpg"
    },
    {
      "src": "photos/pc-setup/IMG_1435.jpg",
      "caption": "",
      "w": 1800,
      "h": 1350,
      "thumb": "photos/_thumbs/pc-setup/IMG_1435.jpg"
    },
    {
      "src": "photos/pc-setup/IMG_1887.jpg",
      "caption": "",
      "w": 1800,
      "h": 1350,
      "thumb": "photos/_thumbs/pc-setup/IMG_1887.jpg"
    },
    {
      "src": "photos/pc-setup/IMG_1891.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/pc-setup/IMG_1891.jpg"
    },
    {
      "src": "photos/pc-setup/IMG_2020.jpg",
      "caption": "",
      "w": 1800,
      "h": 1350,
      "thumb": "photos/_thumbs/pc-setup/IMG_2020.jpg"
    },
    {
      "src": "photos/pc-setup/IMG_2021.jpg",
      "caption": "",
      "w": 1800,
      "h": 1350,
      "thumb": "photos/_thumbs/pc-setup/IMG_2021.jpg"
    },
    {
      "src": "photos/pc-setup/IMG_3098.jpg",
      "caption": "",
      "w": 1800,
      "h": 1350,
      "thumb": "photos/_thumbs/pc-setup/IMG_3098.jpg"
    },
    {
      "src": "photos/pc-setup/IMG_5396.JPG",
      "caption": "",
      "w": 1012,
      "h": 1800,
      "thumb": "photos/_thumbs/pc-setup/IMG_5396.jpg"
    }
  ],
  "perfume": [
    {
      "src": "photos/perfume/IMG_0900.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/perfume/IMG_0900.jpg"
    },
    {
      "src": "photos/perfume/IMG_0901.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/perfume/IMG_0901.jpg"
    },
    {
      "src": "photos/perfume/IMG_2480.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/perfume/IMG_2480.jpg"
    },
    {
      "src": "photos/perfume/IMG_5270.jpg",
      "caption": "",
      "w": 1800,
      "h": 1350,
      "thumb": "photos/_thumbs/perfume/IMG_5270.jpg"
    },
    {
      "src": "photos/perfume/IMG_6039.JPG",
      "caption": "",
      "w": 1012,
      "h": 1800,
      "thumb": "photos/_thumbs/perfume/IMG_6039.jpg"
    },
    {
      "src": "photos/perfume/IMG_6330.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/perfume/IMG_6330.jpg"
    },
    {
      "src": "photos/perfume/IMG_6346.JPG",
      "caption": "",
      "w": 1012,
      "h": 1800,
      "thumb": "photos/_thumbs/perfume/IMG_6346.jpg"
    },
    {
      "src": "photos/perfume/IMG_9012.JPG",
      "caption": "",
      "w": 1012,
      "h": 1800,
      "thumb": "photos/_thumbs/perfume/IMG_9012.jpg"
    },
    {
      "src": "photos/perfume/IMG_9170.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/perfume/IMG_9170.jpg"
    },
    {
      "src": "photos/perfume/IMG_9171%202.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/perfume/IMG_9171%202.jpg"
    },
    {
      "src": "photos/perfume/IMG_9171.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/perfume/IMG_9171.jpg"
    }
  ],
  "photolog": [
    {
      "src": "photos/photolog/B3814B00-A305-40BF-BD45-198DE65EB3B6.JPG",
      "caption": "",
      "w": 1012,
      "h": 1800,
      "thumb": "photos/_thumbs/photolog/B3814B00-A305-40BF-BD45-198DE65EB3B6.jpg"
    },
    {
      "src": "photos/photolog/bf11d6fa-49c1-403f-af35-a5e4849ae04c.JPG",
      "caption": "",
      "w": 1600,
      "h": 900,
      "thumb": "photos/_thumbs/photolog/bf11d6fa-49c1-403f-af35-a5e4849ae04c.jpg"
    },
    {
      "src": "photos/photolog/IMG_0267.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/photolog/IMG_0267.jpg"
    },
    {
      "src": "photos/photolog/IMG_0288.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/photolog/IMG_0288.jpg"
    },
    {
      "src": "photos/photolog/IMG_0596.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/photolog/IMG_0596.jpg"
    },
    {
      "src": "photos/photolog/IMG_0667.jpg",
      "caption": "",
      "w": 1800,
      "h": 1350,
      "thumb": "photos/_thumbs/photolog/IMG_0667.jpg"
    },
    {
      "src": "photos/photolog/IMG_0693.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/photolog/IMG_0693.jpg"
    },
    {
      "src": "photos/photolog/IMG_0835.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/photolog/IMG_0835.jpg"
    },
    {
      "src": "photos/photolog/IMG_1242.jpg",
      "caption": "",
      "w": 1800,
      "h": 1350,
      "thumb": "photos/_thumbs/photolog/IMG_1242.jpg"
    },
    {
      "src": "photos/photolog/IMG_1385.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/photolog/IMG_1385.jpg"
    },
    {
      "src": "photos/photolog/IMG_1540.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/photolog/IMG_1540.jpg"
    },
    {
      "src": "photos/photolog/IMG_1697.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/photolog/IMG_1697.jpg"
    },
    {
      "src": "photos/photolog/IMG_2315.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/photolog/IMG_2315.jpg"
    },
    {
      "src": "photos/photolog/IMG_2985.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/photolog/IMG_2985.jpg"
    },
    {
      "src": "photos/photolog/IMG_3063.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/photolog/IMG_3063.jpg"
    },
    {
      "src": "photos/photolog/IMG_3336.jpg",
      "caption": "",
      "w": 1800,
      "h": 1350,
      "thumb": "photos/_thumbs/photolog/IMG_3336.jpg"
    },
    {
      "src": "photos/photolog/IMG_3402.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/photolog/IMG_3402.jpg"
    },
    {
      "src": "photos/photolog/IMG_3443.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/photolog/IMG_3443.jpg"
    },
    {
      "src": "photos/photolog/IMG_4309.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/photolog/IMG_4309.jpg"
    },
    {
      "src": "photos/photolog/IMG_4709.JPG",
      "caption": "",
      "w": 1012,
      "h": 1800,
      "thumb": "photos/_thumbs/photolog/IMG_4709.jpg"
    },
    {
      "src": "photos/photolog/IMG_4852.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/photolog/IMG_4852.jpg"
    },
    {
      "src": "photos/photolog/IMG_4997.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/photolog/IMG_4997.jpg"
    },
    {
      "src": "photos/photolog/IMG_5049.jpg",
      "caption": "",
      "w": 1152,
      "h": 1785,
      "thumb": "photos/_thumbs/photolog/IMG_5049.jpg"
    },
    {
      "src": "photos/photolog/IMG_5114.JPG",
      "caption": "",
      "w": 1012,
      "h": 1800,
      "thumb": "photos/_thumbs/photolog/IMG_5114.jpg"
    },
    {
      "src": "photos/photolog/IMG_5231.JPG",
      "caption": "",
      "w": 1012,
      "h": 1800,
      "thumb": "photos/_thumbs/photolog/IMG_5231.jpg"
    },
    {
      "src": "photos/photolog/IMG_5381.jpg",
      "caption": "",
      "w": 1800,
      "h": 1350,
      "thumb": "photos/_thumbs/photolog/IMG_5381.jpg"
    },
    {
      "src": "photos/photolog/IMG_6858.JPG",
      "caption": "",
      "w": 1012,
      "h": 1800,
      "thumb": "photos/_thumbs/photolog/IMG_6858.jpg"
    },
    {
      "src": "photos/photolog/IMG_7283.JPG",
      "caption": "",
      "w": 1012,
      "h": 1800,
      "thumb": "photos/_thumbs/photolog/IMG_7283.jpg"
    },
    {
      "src": "photos/photolog/IMG_7314.JPG",
      "caption": "",
      "w": 1012,
      "h": 1800,
      "thumb": "photos/_thumbs/photolog/IMG_7314.jpg"
    },
    {
      "src": "photos/photolog/IMG_7370.JPG",
      "caption": "",
      "w": 1012,
      "h": 1800,
      "thumb": "photos/_thumbs/photolog/IMG_7370.jpg"
    },
    {
      "src": "photos/photolog/IMG_7397.JPG",
      "caption": "",
      "w": 1012,
      "h": 1800,
      "thumb": "photos/_thumbs/photolog/IMG_7397.jpg"
    },
    {
      "src": "photos/photolog/IMG_7442.JPG",
      "caption": "",
      "w": 597,
      "h": 1280,
      "thumb": "photos/_thumbs/photolog/IMG_7442.jpg"
    },
    {
      "src": "photos/photolog/IMG_7556.JPG",
      "caption": "",
      "w": 1012,
      "h": 1800,
      "thumb": "photos/_thumbs/photolog/IMG_7556.jpg"
    },
    {
      "src": "photos/photolog/IMG_7563.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/photolog/IMG_7563.jpg"
    },
    {
      "src": "photos/photolog/IMG_7780.jpg",
      "caption": "",
      "w": 1012,
      "h": 1800,
      "thumb": "photos/_thumbs/photolog/IMG_7780.jpg"
    },
    {
      "src": "photos/photolog/IMG_8101.jpg",
      "caption": "",
      "w": 1012,
      "h": 1800,
      "thumb": "photos/_thumbs/photolog/IMG_8101.jpg"
    },
    {
      "src": "photos/photolog/IMG_8159.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/photolog/IMG_8159.jpg"
    },
    {
      "src": "photos/photolog/IMG_8420.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/photolog/IMG_8420.jpg"
    },
    {
      "src": "photos/photolog/IMG_8498.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/photolog/IMG_8498.jpg"
    },
    {
      "src": "photos/photolog/IMG_8585.jpg",
      "caption": "",
      "w": 1800,
      "h": 1350,
      "thumb": "photos/_thumbs/photolog/IMG_8585.jpg"
    },
    {
      "src": "photos/photolog/IMG_8623.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/photolog/IMG_8623.jpg"
    },
    {
      "src": "photos/photolog/IMG_9151.JPG",
      "caption": "",
      "w": 1012,
      "h": 1800,
      "thumb": "photos/_thumbs/photolog/IMG_9151.jpg"
    },
    {
      "src": "photos/photolog/IMG_9886.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/photolog/IMG_9886.jpg"
    },
    {
      "src": "photos/photolog/IMG_9979.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/photolog/IMG_9979.jpg"
    }
  ],
  "plane-spotting": [
    {
      "src": "photos/plane-spotting/IMG_0842.jpg",
      "caption": "",
      "w": 1800,
      "h": 1350,
      "thumb": "photos/_thumbs/plane-spotting/IMG_0842.jpg"
    },
    {
      "src": "photos/plane-spotting/IMG_2603.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/plane-spotting/IMG_2603.jpg"
    },
    {
      "src": "photos/plane-spotting/IMG_3310.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/plane-spotting/IMG_3310.jpg"
    },
    {
      "src": "photos/plane-spotting/IMG_3432.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/plane-spotting/IMG_3432.jpg"
    },
    {
      "src": "photos/plane-spotting/IMG_3477.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/plane-spotting/IMG_3477.jpg"
    },
    {
      "src": "photos/plane-spotting/IMG_5356.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/plane-spotting/IMG_5356.jpg"
    },
    {
      "src": "photos/plane-spotting/IMG_5444.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/plane-spotting/IMG_5444.jpg"
    },
    {
      "src": "photos/plane-spotting/IMG_5466.jpg",
      "caption": "",
      "w": 1800,
      "h": 1350,
      "thumb": "photos/_thumbs/plane-spotting/IMG_5466.jpg"
    },
    {
      "src": "photos/plane-spotting/IMG_5468.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/plane-spotting/IMG_5468.jpg"
    },
    {
      "src": "photos/plane-spotting/IMG_7214.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/plane-spotting/IMG_7214.jpg"
    },
    {
      "src": "photos/plane-spotting/IMG_7216.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/plane-spotting/IMG_7216.jpg"
    },
    {
      "src": "photos/plane-spotting/IMG_7219.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/plane-spotting/IMG_7219.jpg"
    },
    {
      "src": "photos/plane-spotting/IMG_7502.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/plane-spotting/IMG_7502.jpg"
    },
    {
      "src": "photos/plane-spotting/IMG_7530.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/plane-spotting/IMG_7530.jpg"
    },
    {
      "src": "photos/plane-spotting/IMG_7539.JPG",
      "caption": "",
      "w": 1012,
      "h": 1800,
      "thumb": "photos/_thumbs/plane-spotting/IMG_7539.jpg"
    },
    {
      "src": "photos/plane-spotting/IMG_7761.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/plane-spotting/IMG_7761.jpg"
    },
    {
      "src": "photos/plane-spotting/IMG_8649.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/plane-spotting/IMG_8649.jpg"
    },
    {
      "src": "photos/plane-spotting/IMG_8902.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/plane-spotting/IMG_8902.jpg"
    },
    {
      "src": "photos/plane-spotting/IMG_8980.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/plane-spotting/IMG_8980.jpg"
    },
    {
      "src": "photos/plane-spotting/IMG_8982.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/plane-spotting/IMG_8982.jpg"
    },
    {
      "src": "photos/plane-spotting/IMG_9174.jpg",
      "caption": "",
      "w": 831,
      "h": 1800,
      "thumb": "photos/_thumbs/plane-spotting/IMG_9174.jpg"
    },
    {
      "src": "photos/plane-spotting/IMG_9175.jpg",
      "caption": "",
      "w": 831,
      "h": 1800,
      "thumb": "photos/_thumbs/plane-spotting/IMG_9175.jpg"
    },
    {
      "src": "photos/plane-spotting/IMG_9176.jpg",
      "caption": "",
      "w": 831,
      "h": 1800,
      "thumb": "photos/_thumbs/plane-spotting/IMG_9176.jpg"
    }
  ],
  "pool": [
    {
      "src": "photos/pool/IMG_2600.JPG",
      "caption": "",
      "w": 1012,
      "h": 1800,
      "thumb": "photos/_thumbs/pool/IMG_2600.jpg"
    },
    {
      "src": "photos/pool/IMG_2680.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/pool/IMG_2680.jpg"
    },
    {
      "src": "photos/pool/IMG_2681.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/pool/IMG_2681.jpg"
    },
    {
      "src": "photos/pool/IMG_3716.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/pool/IMG_3716.jpg"
    },
    {
      "src": "photos/pool/IMG_3725.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/pool/IMG_3725.jpg"
    },
    {
      "src": "photos/pool/IMG_4419.JPG",
      "caption": "",
      "w": 1012,
      "h": 1800,
      "thumb": "photos/_thumbs/pool/IMG_4419.jpg"
    },
    {
      "src": "photos/pool/IMG_4453.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/pool/IMG_4453.jpg"
    },
    {
      "src": "photos/pool/IMG_4739.JPG",
      "caption": "",
      "w": 1012,
      "h": 1800,
      "thumb": "photos/_thumbs/pool/IMG_4739.jpg"
    },
    {
      "src": "photos/pool/IMG_4917.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/pool/IMG_4917.jpg"
    },
    {
      "src": "photos/pool/IMG_5056.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/pool/IMG_5056.jpg"
    },
    {
      "src": "photos/pool/IMG_5057.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/pool/IMG_5057.jpg"
    },
    {
      "src": "photos/pool/IMG_5169.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/pool/IMG_5169.jpg"
    },
    {
      "src": "photos/pool/IMG_5249.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/pool/IMG_5249.jpg"
    },
    {
      "src": "photos/pool/IMG_5497.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/pool/IMG_5497.jpg"
    },
    {
      "src": "photos/pool/IMG_5498.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/pool/IMG_5498.jpg"
    },
    {
      "src": "photos/pool/IMG_5949.JPG",
      "caption": "",
      "w": 1012,
      "h": 1800,
      "thumb": "photos/_thumbs/pool/IMG_5949.jpg"
    },
    {
      "src": "photos/pool/IMG_6295.JPG",
      "caption": "",
      "w": 1012,
      "h": 1800,
      "thumb": "photos/_thumbs/pool/IMG_6295.jpg"
    },
    {
      "src": "photos/pool/IMG_6942.JPG",
      "caption": "",
      "w": 1012,
      "h": 1800,
      "thumb": "photos/_thumbs/pool/IMG_6942.jpg"
    },
    {
      "src": "photos/pool/IMG_7907.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/pool/IMG_7907.jpg"
    },
    {
      "src": "photos/pool/IMG_7912.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/pool/IMG_7912.jpg"
    },
    {
      "src": "photos/pool/IMG_7913.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/pool/IMG_7913.jpg"
    },
    {
      "src": "photos/pool/IMG_8480.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/pool/IMG_8480.jpg"
    },
    {
      "src": "photos/pool/IMG_8487.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/pool/IMG_8487.jpg"
    }
  ],
  "robotics": [
    {
      "src": "photos/robotics/47af9530-da79-4b5e-a398-1a05b852b2de.JPG",
      "caption": "",
      "w": 1280,
      "h": 960,
      "thumb": "photos/_thumbs/robotics/47af9530-da79-4b5e-a398-1a05b852b2de.jpg"
    },
    {
      "src": "photos/robotics/IMG_0929.JPG",
      "caption": "",
      "w": 1012,
      "h": 1800,
      "thumb": "photos/_thumbs/robotics/IMG_0929.jpg"
    },
    {
      "src": "photos/robotics/IMG_1772.jpg",
      "caption": "",
      "w": 831,
      "h": 1800,
      "thumb": "photos/_thumbs/robotics/IMG_1772.jpg"
    },
    {
      "src": "photos/robotics/IMG_1798.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/robotics/IMG_1798.jpg"
    },
    {
      "src": "photos/robotics/IMG_1808.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/robotics/IMG_1808.jpg"
    },
    {
      "src": "photos/robotics/IMG_4102.jpg",
      "caption": "",
      "w": 1800,
      "h": 1350,
      "thumb": "photos/_thumbs/robotics/IMG_4102.jpg"
    },
    {
      "src": "photos/robotics/IMG_4459.jpg",
      "caption": "",
      "w": 1800,
      "h": 1350,
      "thumb": "photos/_thumbs/robotics/IMG_4459.jpg"
    },
    {
      "src": "photos/robotics/IMG_9588.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/robotics/IMG_9588.jpg"
    }
  ],
  "sarsan-aviation": [
    {
      "src": "photos/sarsan-aviation/IMG_3402.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/sarsan-aviation/IMG_3402.jpg"
    },
    {
      "src": "photos/sarsan-aviation/IMG_3403.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/sarsan-aviation/IMG_3403.jpg"
    },
    {
      "src": "photos/sarsan-aviation/IMG_9547.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/sarsan-aviation/IMG_9547.jpg"
    },
    {
      "src": "photos/sarsan-aviation/IMG_9554.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/sarsan-aviation/IMG_9554.jpg"
    },
    {
      "src": "photos/sarsan-aviation/IMG_9556.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/sarsan-aviation/IMG_9556.jpg"
    },
    {
      "src": "photos/sarsan-aviation/IMG_9558.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/sarsan-aviation/IMG_9558.jpg"
    },
    {
      "src": "photos/sarsan-aviation/IMG_9561.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/sarsan-aviation/IMG_9561.jpg"
    },
    {
      "src": "photos/sarsan-aviation/IMG_9563.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/sarsan-aviation/IMG_9563.jpg"
    },
    {
      "src": "photos/sarsan-aviation/IMG_9577.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/sarsan-aviation/IMG_9577.jpg"
    },
    {
      "src": "photos/sarsan-aviation/IMG_9580.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/sarsan-aviation/IMG_9580.jpg"
    },
    {
      "src": "photos/sarsan-aviation/IMG_9586.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/sarsan-aviation/IMG_9586.jpg"
    },
    {
      "src": "photos/sarsan-aviation/IMG_9598.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/sarsan-aviation/IMG_9598.jpg"
    }
  ],
  "worlds-scholars-cup": [
    {
      "src": "photos/worlds-scholars-cup/IMG_1463.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/worlds-scholars-cup/IMG_1463.jpg"
    },
    {
      "src": "photos/worlds-scholars-cup/IMG_1485.jpg",
      "caption": "",
      "w": 1800,
      "h": 1350,
      "thumb": "photos/_thumbs/worlds-scholars-cup/IMG_1485.jpg"
    },
    {
      "src": "photos/worlds-scholars-cup/IMG_1489.jpg",
      "caption": "",
      "w": 1800,
      "h": 1350,
      "thumb": "photos/_thumbs/worlds-scholars-cup/IMG_1489.jpg"
    },
    {
      "src": "photos/worlds-scholars-cup/IMG_1496.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/worlds-scholars-cup/IMG_1496.jpg"
    },
    {
      "src": "photos/worlds-scholars-cup/IMG_1525.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/worlds-scholars-cup/IMG_1525.jpg"
    },
    {
      "src": "photos/worlds-scholars-cup/IMG_1526.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/worlds-scholars-cup/IMG_1526.jpg"
    },
    {
      "src": "photos/worlds-scholars-cup/IMG_1541.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/worlds-scholars-cup/IMG_1541.jpg"
    },
    {
      "src": "photos/worlds-scholars-cup/IMG_1614.JPG",
      "caption": "",
      "w": 1800,
      "h": 1012,
      "thumb": "photos/_thumbs/worlds-scholars-cup/IMG_1614.jpg"
    },
    {
      "src": "photos/worlds-scholars-cup/IMG_1745.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/worlds-scholars-cup/IMG_1745.jpg"
    },
    {
      "src": "photos/worlds-scholars-cup/IMG_3610.jpg",
      "caption": "",
      "w": 1800,
      "h": 1350,
      "thumb": "photos/_thumbs/worlds-scholars-cup/IMG_3610.jpg"
    },
    {
      "src": "photos/worlds-scholars-cup/IMG_3612.jpg",
      "caption": "",
      "w": 1800,
      "h": 1350,
      "thumb": "photos/_thumbs/worlds-scholars-cup/IMG_3612.jpg"
    },
    {
      "src": "photos/worlds-scholars-cup/IMG_3617.jpg",
      "caption": "",
      "w": 1350,
      "h": 1800,
      "thumb": "photos/_thumbs/worlds-scholars-cup/IMG_3617.jpg"
    }
  ]
};
